language: go
go:
  - 1.20.x
  - 1.21.x
  - master

arch:
  - amd64
  - arm64

matrix:
 fast_finish: true
 allow_failures:
   - go: master

go_import_path: github.com/weaviate/hdf5

sudo: false

addons:
  apt:
    packages:
      - libhdf5-serial-dev

env:
  global:
    - GODEBUG=cgocheck=0

script:
 - go get -d -t -v ./...
 - go install -v ./...
 - go test -v ./...

